### ISSUE TITLE
Dynamic array

### ISSUE THREAD

**Issue by mauriciosoares** [igorapa/form-storage#1]
Hey!

What about getting the form dynamically according to the configs when you init the plugin?

like this

```javascript
new Storage('#my-form');
```

**Comment by igorapa** [comment]
Hey @mauriciosoares thank for your suggestion! I love it.

What do you think about [this way](https://github.com/igorapa/form-storage/blob/master/index.html#L24-L28)?

**Comment by mauriciosoares** [comment]
That's cool, But do you think you really need to manually call `init`? 

Maybe you can trigger it when the instance is created... just a thought... You totally solved the problem.

:)
