### ISSUE TITLE
parse objects to JSON before save in localStorage

### ISSUE THREAD

**Issue by mauriciosoares** [igorapa/form-storage#10]
Hey :)

Today you're saving each value from the inputs in different localStorage fields... That's kinda messy in my opinion...

Why don't you parse all fields on `focusOut`, and always save in the same field from the localStorage? You can do `JSON.stringify` to do the trick, and when you retrieve the data you could use `JSON.parse`.

Both ways will work, but maybe this way the localStorage will be a little bit more organized... Imagine if I have 50 fields in my form, the localStorage will create 50 different indexes.

**Comment by weslleyaraujo** [comment]
awesome idea @mauriciosoares ..
by doing this it will also make sure that the "plugin" is not messing up with any data already saved into the localStorage..

it can be also be added a namespace on localStorage key like:

```js
"form-storage:data": "{ ... parsed JSON ... }"
```

💪

**Comment by mauriciosoares** [comment]
🐵🙊🙉

+1

**Comment by igorapa** [comment]
Hey @mauriciosoares and @weslleyaraujo 
I just changed how you told me!
Now, I think it's better.

What you guys think?

**Comment by mauriciosoares** [comment]
good

**Comment by mauriciosoares** [comment]
I think now it makes more sense :)

**Comment by igorapa** [comment]
![Delicious](https://cldup.com/VLV0ns1sn6.gif)
