### ISSUE TITLE
Get fields by name

### ISSUE THREAD

**Issue by mauriciosoares** [igorapa/form-storage#2]
Hey, it's me again...

You could track down all fields in the form if they have the `name` attribute...

Since we have some inconsistency in forms fields (like `input`, `select`, `textarea`), at least we know that all form fields *should* have the `name` attribute.

maybe something like this:

```javascript
this.inputs = this.form.querySelectorAll('[name]');
```

**Comment by igorapa** [comment]
Hey my brother, I'd like visit you in Boituva.

I did [this way](https://github.com/igorapa/form-storage/blob/master/script.js#L16-L20), I don't know what do you think, I hope you like it.

**Comment by mauriciosoares** [comment]
Hey, I see a possible problem with your code...

in the method `saveData`, if the input field has no `name` attribute, which key will it save in the localStorage? probably `undefined`...

That's why I think you should query input fields by `[name]`, this way you'll only get inputs that has the name attribute on it... also you'll not have to do the `isSubmit ` check, since submit buttons don't use the `name` attribute.

I'd change this line https://github.com/igorapa/form-storage/blob/master/script.js#L20 to this:

```javascript
[].forEach.call(this.el.querySelectorAll('[name]'), this.addEvent.bind(this));
```

this way in the `saveData` method you'll guarantee that all fields has the `name` attribute.

**Comment by mauriciosoares** [comment]
Also, before you save the data in the localStorage, you could check if the element is visible...

There's a bunch of `hidden` input fields that I don't think they shouldn't be stored in the localStorage... what you think?

**Comment by igorapa** [comment]
Hey man, I just changed how you said.
Now, I think it's ok.

What do you think?

**Comment by mauriciosoares** [comment]
Cool!
<img width="279" alt="screen shot 2015-07-20 at 13 03 42" src="https://cloud.githubusercontent.com/assets/2321259/9097828/6a5cbace-3b9c-11e5-93dd-8825a35de872.png">
