### ISSUE TITLE
Get submit event instead of click

### ISSUE THREAD

**Issue by weslleyaraujo** [igorapa/form-storage#3]
Hey,

would be nice to have a  simple improvement by getting the `submit` event of the form instead of the `click` event on the submit button..

by doing this any submit action on the form (like enter keypress or something even triggered by javascript) would also do the job 😎

**Comment by igorapa** [comment]
I don't understand very well, maybe you can give example or explain to me , ok?

**Comment by weslleyaraujo** [comment]
at your actual code you are doing something like this:

```js
this.submit.addEventListener('click', this.onClick.bind(this));
````

by doing this you only erase the data from local storage if the user clicks on the submit button,
but if for example the user just hit the "enter" key (which will submit the form anyway) your callback will not be executed..

you could prevent this by attaching an submit event to the form like:

```js
this.el.addEventListener('submit', this.onSubmit.bind(this));
```

and then you would erase the data from local storage, this would work with click on submits or anything 😉

**Comment by igorapa** [comment]
Now I get it, I was still adding the event in submit element, not in form!
Once again thank you. 🍆
