### ISSUE TITLE
Use "keyup" event on each input in order to save it

### ISSUE THREAD

**Issue by weslleyaraujo** [igorapa/form-storage#4]
What you think of getting the `keyup` event from each to always save it info instead of using a `setTimeout`?

I don't know if it is a good idea since it will keep saving every time, but by doing this you will never lose data..

**Comment by igorapa** [comment]
Hey @weslleyaraujo what do you think this that I did?

**Comment by weslleyaraujo** [comment]
Awesome approach @igorapa :)

bind 💖

**Comment by igorapa** [comment]
Thank for your suggestion, I learned much.
Issue done!
