### ISSUE TITLE
use "removeItem" method instead of delete

### ISSUE THREAD

**Issue by weslleyaraujo** [igorapa/form-storage#8]
Hey, 
maybe you could use `removeItem` instead of delete a key from localStorage..

what you think?
 ([see](https://developer.mozilla.org/en-US/docs/Web/API/Storage/removeItem))

**Comment by weslleyaraujo** [comment]
I also noticed in some points the values from localStorage are retrieving like:

```js
localStorage["some-key"]
```

you could also use the [getItem](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem) instead :8ball:

**Comment by igorapa** [comment]
Hey brother, about the first topic, I had made this, but never had use the method `delete`, I think is funny use this moment. But ok, I already changed.

Thank you very much! 🍻

**Comment by weslleyaraujo** [comment]
Awesome @igorapa 😍

more and more learning!

**Comment by igorapa** [comment]
I need tell you one thing, YOU ARE A MONSTER!
I just changed to getItem (feel good meme)

**Comment by igorapa** [comment]
![nice](https://cldup.com/R2wtOTmtJv.png)
